#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){
    qrcode.fetch("http://www.longurlmaker.com/go?id=UAOJNVKBMQUGPYZKCQZRZKJEXRCRXMRSMFBZBMBODWUSVTDXJCPJMYOKQQBODSGPYHPZURNXNIQIBUGLWVUJUIUKZVYCOFSNMIMHZAEMIVVKPCVMYPVTYPEYLDBAITNUCACBBHOKCKUSMPEKFADEPHCBLEBTXPOZPQBQXPBAZVSMLXXRXAVMIYNTCPNAEBAURBKORMORHHDTEAKBBGOKEBEGRRHVSHPKIAYZNNQUVUOZUYAVEOGJQKQIBXEUEUEMUDMHRDCMXQLRPMNUBUDSETAGQEAUZFHTITBZXEMUVYMLKAFMUJFYCFFTKGOJLWDUPFUMKGHGETRPTXCNGHMJNRCYXRIINLCDRWQCDXIHRZXKWZYDHKMUCPSZHAIUMLYEIOGMMPUDPROMRNPYXCTARLAYMJTYURDDGKPSZKWOBLBTYQRWSKWKWWJIFCHAULEAVUTUEQJFBKZZBQWUBSEYPNGUQOVKZZKVTEPXUZDVKCVLTRFUKKTZXZTOOPYOOJJINYGHYJDJMYUFQAAAKTZITTXHIVVXEEGSDMZCVDLICGNSGNTRHSAAMXIVSDTXIZPMLPOHTZPVFCNMQHEXZEYMCGHVKBSSAIEMYTTRTJMZMALCHQAHUZUWFBRPCKIDTNPSGIJASWZEWLHEBHMVGGSMIKBLVKOPXDHEMREENEIKPQPQXBMEHFRQQTBLDPBBTIFGZKLNOUYDKNUIPGNXMENCXOOBEPCYYHEYRQLFKJJUXDCMKQJWUWZSLNTQCVOBCTZUJKATUJOSNRFXHOUBLTTXGNNJIBKLVKGEVGYQQMIEENCLCWMNQGKXTXHCZSNVCTZXAYNRLVVPJXALUNZLUKIOIPQHHDDKXDHXBUPMQKCZIDLCQKNLVWZDLPLTTOERRLPSGEFWOIWXLIZCTNNOJNRVDCPXRTOIEEBKIHHXPDUBLUDEHRTQFKMINBFEUUNZYOKHVRELVZMHTQMBIFRNQEWDFCIAWVZVJKCFBHRXGEEAUQBDWTRMXNQCQYDMUDHENKKORBMXFQXAHYEESVQPJHSZGVMAYUFLEPAWRMTWDRXKQCPIXGXHNPHULTVJOAVTQWPHJJEMACXREMABSXJGNQAZKVJZWESMAHTJQYWRATJEGJGYHPEVGFUQADQWHIJIQDSGBOYBIHFORLNYBSTHXNYYQOVYWEHMHZTIOSKXAPMRBZPCSJKPWIONXJLTOTGWSAFHTPFTFRLGQAJIKTYGCMTZWFTLYAHRAMZUCEOHVZOMAYVKRUQUHKTDPMPONWFOJFIMJWTFVIRWGNGYHXTPHMSXZILNFRBOWJAGGULCDDYKQEJYBCNJPGGPOSCTKDIHNJNTEYVHCTSSYBRAEEJTLQJZJLTTOCBCLOVQNRXPLQIJSZKWETQPKZPTKJNZLOCXDXNQPLFABOKTNVQSOGHZGXSRGGQSVSPYQCOGNUHPISJWNZOCGWBMTUDZBURWNHUDJIKXDRNMJWIWWWZCTAOMVSMWMDSZLMDVVNTYFGKODTLZQKBJLQVGIHCVLVUWHYSDMLBRRMGUGSUWDVGOMCVUKYPVTKSAIKDVWFMNSTIYLCVOYBCKEYFOWVKPGCQPNTKJZXXRQFQBIMQHOTRSRXGNTQCZTSOHMZQLWODMUUOCGEJUXBMOZSCSJERDWGKJFBUCPYPJSDMYIWSGYFVXYXQHBIKYOUHUVCXLAMVSPIQYEJEDOZBMWRUYZEWOZEJVGGGGSCZIKQGPZLSOKTAHKUFKZCYYHIUNOBUHDUPNKWDKHVYSPZAAUGKTIJSQRMDGNYNRSDFDAINIELAULBUFHFZQPRGHEKNRIBJBFOEFWRNADOUPPPUWVTNKLTRPDFHLHQNMERSBJGCNUXCKMXHHRUSCNJRRPZDWQQJUIBWSHYFCVINIFVQWPIZDSRUHQXEGONBWPYOXWUASCNAIIRFYZFBSWWANTEUISVEITTFQNFIQTJZCAEAZKCSGYSTSWNAPJFXDYCTLICCCLBEMGFLQHEWGWQZSEAINFFQDHKPQMRSYTWKZCWQJANQWDPPHPXVUCMYKWOBJG");
}

//--------------------------------------------------------------
void ofApp::update(){

}

//--------------------------------------------------------------
void ofApp::draw(){
    if(qrcode.isAllocated())qrcode.draw(0,0);
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){

}

//--------------------------------------------------------------
void ofApp::keyReleased(int key){

}

//--------------------------------------------------------------
void ofApp::mouseMoved(int x, int y ){

}

//--------------------------------------------------------------
void ofApp::mouseDragged(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::mousePressed(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::mouseReleased(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::mouseEntered(int x, int y){

}

//--------------------------------------------------------------
void ofApp::mouseExited(int x, int y){

}

//--------------------------------------------------------------
void ofApp::windowResized(int w, int h){

}

//--------------------------------------------------------------
void ofApp::gotMessage(ofMessage msg){

}

//--------------------------------------------------------------
void ofApp::dragEvent(ofDragInfo dragInfo){ 

}
